
# import pyttsx3

# def text_to_speech(text,filename="voicenote.mp3"):
#     engine = pyttsx3.init()
#     engine.save_to_file(text, filename)
#     engine.runAndWait()
#     print(f"Audio saved as {filename}")

# text = """
# Hey! This is an automated voice note generated by me using Pytob.
# I am learning automation and crushing it!
# """

# text_to_speech(text, "note1.mp3")


from gtts import gTTS
import pyttsx3
import os
# text to speech using gTTS and saving as mp3
text = """
Hey! This is an automated voice note generated by me using gTTS.
I am learning automation and crushing it!"""

speech = gTTS(text=text, lang='en', slow=False)
speech.save("voicenote_gTTS.mp3")
print("Audio saved as voicenote_gTTS.mp3")

# text to speech using pyttsx3 without saving

engine = pyttsx3.init()
engine.say("generated using pyttsx3 without saving")
engine.runAndWait()
